@rootUrl = http://localhost:8000

###check if server is running
GET {{rootUrl}}

###creating a new user

POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName": "bibek",
    "lName": "malla",
    "email": "b@k.com",
    "password": "texy",
    "role": "user"

}

###login a user
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "b@k.com",
    "password": "texy"

}

