@rootUrl = http://localhost:3000

###check if server is running
GET {{rootUrl}}

###creating a new user

POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName": "Bibek",
    "lName": "Hamal",
    "email": "b@e.com",
    "password": "text",
    "role": "admin"

}

###login a user
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "b@e.com",
    "password": "text"

}

